#!/usr/bin/env python3
#
# PartCAD, 2026
#
# Licensed under Apache License, Version 2.0.
#

import asyncio
import os
import re
import sys
import tempfile

import pytest

import partcad as pc
from partcad import assembly_factory_assy, assembly_guide
from partcad import document as pc_document
from partcad.assembly import Assembly, AssemblyChild
from partcad.exception import NotAnAssemblyFileError, NotManufacturableError
from partcad.geom import Location

# The example package whose assemblies are put together by connecting ports,
# which is what an assembly instruction book is made of.
CONNECT_PACKAGE = "//feature_interface"
CONNECT_ASSEMBLY = "connect-ports"


def make_assembly(name="test", **config):
    config = dict({"name": name, "type": "assy"}, **config)
    return Assembly("//pkg", config)


#
# The document model
#


def test_document_markdown():
    """Every kind of block, written down as markdown"""
    document = pc_document.Document(
        title="widget",
        pages=[
            pc_document.Page(
                blocks=[
                    pc_document.Heading("widget", level=1),
                    pc_document.Paragraph("A widget."),
                    pc_document.Properties([("Package", "`//pkg`")]),
                    pc_document.Heading("//other", level=3, url="../other/README.md"),
                    pc_document.Table(
                        columns=["Part", "Count", "Description"],
                        aligns=["left", "right", "left"],
                        rows=[["bolt", 2, "a | b\nc"]],
                    ),
                    pc_document.ImageRow([pc_document.Image(file="/tmp/widget.svg", src="./widget.svg")]),
                    pc_document.LinkList([("PartCAD", "https://partcad.org/")]),
                ]
            )
        ],
        footer=pc_document.GENERATED_BY,
    )

    lines = pc_document.render_markdown(document)

    assert lines[0] == "# widget"
    assert "A widget." in lines
    assert "Package: `//pkg`" in lines
    assert "### [//other](../other/README.md)" in lines
    assert "| Part | Count | Description |" in lines
    assert "| --- | ---: | --- |" in lines
    # A cell keeps the table one row per line: no bare pipes, no newlines.
    assert "| bolt | 2 | a \\| b<br/>c |" in lines
    assert '<img src="./widget.svg" alt="" style="%s">' % pc_document.MARKDOWN_IMAGE_STYLE in lines
    assert "- [PartCAD](https://partcad.org/)" in lines
    assert lines[-1] == "*Generated by [PartCAD](https://partcad.org/)*"


def test_document_html():
    """The HTML document is one file that shows one page at a time"""
    document = pc_document.Document(
        title="widget & co",
        pages=[
            pc_document.Page(title="Title", blocks=[pc_document.Heading("widget & co")]),
            pc_document.Page(title="Links", blocks=[pc_document.LinkList([("PartCAD", "https://partcad.org/")])]),
        ],
        footer=pc_document.GENERATED_BY,
    )

    html = pc_document.render_html(document)

    assert "<title>widget &amp; co</title>" in html
    assert '<section class="page" id="page-1" data-title="Title">' in html
    assert '<section class="page" id="page-2" data-title="Links">' in html
    assert "<h1>widget &amp; co</h1>" in html
    assert '<a href="https://partcad.org/">PartCAD</a>' in html
    # The pages are flipped through rather than scrolled.
    assert 'id="prev"' in html and 'id="next"' in html
    assert "ArrowLeft" in html and "ArrowRight" in html


def test_document_html_inlines_images():
    """An HTML document carries its illustrations rather than pointing at them"""
    with tempfile.TemporaryDirectory() as directory:
        path = os.path.join(directory, "widget.svg")
        with open(path, "w") as f:
            f.write('<svg xmlns="http://www.w3.org/2000/svg"/>')

        document = pc_document.Document(
            pages=[pc_document.Page(blocks=[pc_document.ImageRow([pc_document.Image(file=path)])])]
        )
        html = pc_document.render_html(document)

    assert "data:image/svg+xml;base64," in html
    # The file it was made from is gone by now, and the document still has it.
    assert path not in html


def test_document_to_data_is_plain():
    """The PDF renderer is handed plain data, not objects"""
    document = pc_document.Document(
        title="widget",
        pages=[
            pc_document.Page(
                blocks=[
                    pc_document.Heading("widget"),
                    pc_document.Table(columns=["Part"], rows=[["bolt"]]),
                    pc_document.ImageRow([pc_document.Image(file="/tmp/widget.svg", caption="widget")]),
                ]
            )
        ],
    )

    data = pc_document.to_data(document)

    assert data["title"] == "widget"
    blocks = data["pages"][0]["blocks"]
    assert blocks[0] == {"type": "heading", "text": "widget", "level": 1, "url": None}
    assert blocks[1]["rows"] == [["bolt"]]
    assert blocks[2]["images"] == [{"path": "/tmp/widget.svg", "caption": "widget", "alt": ""}]


def test_document_to_data_embeds_images_on_request():
    """A reader with no file system in reach is handed the pictures themselves

    The IDE's viewer is a webview on the other side of a JSON-RPC connection, and
    the illustrations of an instruction book live in a temporary directory that
    is deleted as soon as the document has been built.
    """
    with tempfile.TemporaryDirectory() as directory:
        path = os.path.join(directory, "widget.svg")
        with open(path, "w") as f:
            f.write('<svg xmlns="http://www.w3.org/2000/svg"/>')

        document = pc_document.Document(
            pages=[
                pc_document.Page(
                    blocks=[pc_document.ImageRow([pc_document.Image(file=path, caption="widget", alt="widget")])]
                )
            ]
        )
        data = pc_document.to_data(document, embed_images=True)

    (image,) = data["pages"][0]["blocks"][0]["images"]
    assert image["src"].startswith("data:image/svg+xml;base64,")
    assert image["caption"] == "widget"
    # The file it was made from is gone by now, and the document still has it.
    assert "path" not in image


def test_pdf_table_row_never_outgrows_the_table():
    """A row wider than the table's columns stays on the page

    Every cell has to be drawn, and the row has to keep the width of the table:
    a cell past the right edge of the page is hidden just as surely as one that
    was dropped.
    """
    # 'wrapper_layout', not the wrapper that draws the PDF: the latter imports
    # reportlab, which is installed in the sandbox the PDF is composed in and
    # not on the host the tests run on.
    sys.path.insert(0, os.path.join("partcad", "src", "partcad", "wrappers"))
    import wrapper_layout

    widths, aligns = [100.0, 50.0, 200.0], ["left", "right", "left"]
    total = sum(widths)

    # The usual case is left exactly as it was.
    assert wrapper_layout.fit_row(["a", "b", "c"], widths, aligns) == (widths, aligns)

    for count in (4, 6):
        row = ["cell"] * count
        row_widths, row_aligns = wrapper_layout.fit_row(row, widths, aligns)
        assert len(row_widths) >= count
        assert len(row_aligns) >= count
        assert row_widths == pytest.approx([100.0, 50.0] + [200.0 / (count - 2)] * (count - 2))
        assert sum(row_widths) == pytest.approx(total)


#
# What can be documented
#


def test_guide_requires_an_assy():
    """Only an assembly with declared steps gets an instruction book"""
    with pytest.raises(NotAnAssemblyFileError):
        assembly_guide.check_source(make_assembly(type="file"))
    with pytest.raises(NotAnAssemblyFileError):
        assembly_guide.check_source(make_assembly(type="alias"))

    # No exception: this one is an ASSY and is meant to be built.
    assembly_guide.check_source(make_assembly())


def test_guide_requires_manufacturability():
    """An assembly nobody is meant to build is refused unless asked twice"""
    assembly = make_assembly(manufacturable=False)

    with pytest.raises(NotManufacturableError) as error:
        assembly_guide.check_source(assembly)
    assert "--ignore-manufacturability" in str(error.value)

    assembly_guide.check_source(assembly, ignore_manufacturability=True)


def test_guide_resolves_aliases():
    """An alias is documented as whatever it points at"""
    ctx = pc.init("examples")
    alias = ctx._get_assembly("//produce_assembly_assy:partcad_logo")
    assert alias is not None
    assert alias.config.get("type") == "alias"

    resolved = assembly_guide.resolve_alias(ctx, alias)

    assert resolved.name == "logo"
    assert resolved.config.get("type") == "assy"
    # Which is what makes it documentable at all.
    assembly_guide.check_source(resolved, ignore_manufacturability=True)


#
# The steps
#


def test_step_source_looks_through_the_root_container():
    """The container an ASSY file's root node creates is not a sub-assembly

    Every ASSY file holds its items in a container node, so the assembly a
    package declares has a single embedded assembly as its only child. That
    wrapper is the assembly itself under another name.
    """
    inner = make_assembly("outer:None", child=True)
    inner.add(make_assembly("a"), "a")
    inner.add(make_assembly("b"), "b")
    outer = make_assembly("outer")
    outer.add(inner, None)

    assert assembly_guide._step_source(outer) is inner
    # An assembly that holds a single part is not a wrapper around anything.
    assert assembly_guide._step_source(inner) is inner


def test_exploded_location_moves_the_item_along_the_joint():
    """An exploded view holds the item off the joint by the gap it is given"""
    step = assembly_guide.GuideStep(
        number=1,
        item=make_assembly("a"),
        item_name="a",
        location=Location([[1, 2, 3], [0, 0, 1], 0]),
        counterpart=make_assembly("b"),
        counterpart_name="b",
        counterpart_location=Location(),
        direction=(0.0, 0.0, 1.0),
        distance=10.0,
    )

    translation = step.exploded_location().translation

    assert translation == pytest.approx((1.0, 2.0, 13.0))


def test_exploded_is_validated_where_it_is_declared():
    """A gap that is not a number is reported and dropped, not carried onwards

    An ASSY file is not validated against a schema, so this is the only place
    that can tell the reader which file the bad value is in. Left to reach the
    renderer, it would surface as a ValueError naming neither.
    """
    factory = assembly_factory_assy.AssemblyFactoryAssy.__new__(assembly_factory_assy.AssemblyFactoryAssy)
    factory.name = "widget"

    assert factory._exploded_distance(None, "bracket") is None
    assert factory._exploded_distance(30, "bracket") == 30.0
    assert factory._exploded_distance("30", "bracket") == 30.0
    # Neither of these is a distance; the step falls back to the default gap.
    assert factory._exploded_distance("far", "bracket") is None
    assert factory._exploded_distance(True, "bracket") is None


def test_prose_folds_the_line_breaks_of_the_file():
    """Text hand-wrapped in an ASSY file reads the same in all three formats

    HTML turns a line break into a '<br/>' and the PDF starts a new line, while
    markdown folds it away, so the wrapping of the file would otherwise be a
    different document in each of them.
    """
    assert assembly_guide._prose(None) == []
    assert assembly_guide._prose("   \n  ") == []
    assert assembly_guide._prose("One sentence,\nwrapped by the file.") == ["One sentence, wrapped by the file."]
    # A blank line is the break that was meant, and starts a paragraph.
    assert assembly_guide._prose("First.\n\nSecond.\n") == ["First.", "Second."]


def test_build_section_carries_the_words_of_the_assy_file(monkeypatch):
    """What each node of the file says about itself reaches the pages showing it

    The first item is placed by no step - there is nothing yet to place it
    against - so the assembly's own page is the only place its description can
    go.
    """

    async def no_geometry(ctx, step):
        """The gap between two items needs a CAD runtime; this test needs none."""

    monkeypatch.setattr(assembly_guide, "_resolve_step_geometry", no_geometry)

    content = make_assembly("widget:None", child=True)
    content.children.append(AssemblyChild(make_assembly("bracket"), "bracket", Location(), description="The fixture."))
    content.children.append(
        AssemblyChild(
            make_assembly("screw"),
            "screw",
            Location(),
            comment="Start it by hand.",
            connection={"target": "bracket"},
            description="The screw that holds it down.",
        )
    )

    section = asyncio.run(assembly_guide._build_section(None, content, content))

    assert (section.base_name, section.base_description) == ("bracket", "The fixture.")
    (step,) = section.steps
    assert step.item_description == "The screw that holds it down."
    assert step.comment == "Start it by hand."


def test_section_page_names_the_item_to_start_with():
    """The assembly's own page says what to pick up first, and what it is"""
    section = assembly_guide.GuideSection(
        assembly=make_assembly("widget", desc="A widget.\nMade of two parts."),
        name="widget",
        base_name="bracket",
        base_description="The fixture everything else is mounted on.",
    )

    (page,) = asyncio.run(assembly_guide._section_pages(None, section, assembly_guide.ImageSource(), 1))
    texts = [block.text for block in page.blocks if isinstance(block, pc_document.Paragraph)]

    assert texts == [
        "A widget. Made of two parts.",
        "Start with bracket.",
        "The fixture everything else is mounted on.",
    ]


def test_step_page_shows_what_the_file_says_about_the_step():
    """A step's page carries the node's description and the connection's comment

    The comment is marked as a note: it is context around the step and never the
    step itself (see docs/source/assy.rst), and the reader has to be able to
    tell which of the paragraphs is the thing to do.
    """
    step = assembly_guide.GuideStep(
        number=1,
        item=make_assembly("screw"),
        item_name="screw",
        location=Location(),
        counterpart=make_assembly("bracket"),
        counterpart_name="bracket",
        counterpart_location=Location(),
        item_description="The screw that holds it down.",
        comment="Start this screw by hand:\nthe plate flexes if it is torqued down first.",
    )
    section = assembly_guide.GuideSection(assembly=make_assembly("widget"), name="widget", steps=[step])

    page = asyncio.run(assembly_guide._step_page(section, step, assembly_guide.ImageSource()))
    texts = [block.text for block in page.blocks if isinstance(block, pc_document.Paragraph)]

    assert texts == [
        "The screw that holds it down.",
        "Add screw to bracket.",
        "Note: Start this screw by hand: the plate flexes if it is torqued down first.",
    ]


def test_step_description_names_the_ports():
    """A step says what is connected to what"""
    step = assembly_guide.GuideStep(
        number=1,
        item=make_assembly("screw"),
        item_name="screw",
        location=Location(),
        counterpart=make_assembly("bracket"),
        counterpart_name="bracket",
        counterpart_location=Location(),
        connection={"with_port": "thread", "to_port": "hole"},
    )

    assert step.description() == "Connect the thread port of screw to the hole port of bracket."


@pytest.mark.slow
def test_connection_is_recorded_for_connected_items():
    """Placing an item by connecting it records what it was connected to

    Without this, nothing downstream can tell which two items a step joins: the
    resulting placement is just a location like any other.
    """
    ctx = pc.init("examples")
    assembly = ctx._get_assembly("//feature_interface:connect-ports")
    assert assembly is not None
    asyncio.run(assembly.do_instantiate())
    content = assembly_guide._step_source(assembly)

    connections = [child.connection for child in content.children if child.connection]
    assert len(connections) == len(content.children) - 1

    first = connections[0]
    assert first["target"] == "example-bracket"
    assert first["with_port"] and first["to_port"]
    # Where the two ports meet, and which way to pull them apart.
    assert len(first["point"]) == 3
    assert len(first["direction"]) == 3


def test_links_page_points_at_the_package_and_its_suppliers():
    """The closing page links to where the parts came from

    Only to the packages that supply enough of them to be worth a look: whoever
    is assembling this needs to know where to get four of the parts, not which
    package the one bolt came from.
    """
    ctx = pc.init("examples")
    prj = ctx.get_project("//produce_assembly_assy")
    assembly = prj.get_assembly("logo")
    grouped = asyncio.run(assembly.get_bom_grouped_async())

    page = assembly_guide._links_page(prj, assembly, grouped, prj.config_dir)
    items = page.blocks[-1].items
    texts = [text for text, _ in items]

    assert ("PartCAD", pc_document.PARTCAD_URL) in items
    assert any(text.startswith("This assembly: logo") for text in texts)
    assert any(text.startswith("This package: ") for text in texts)
    # Two bones and two head halves come from one package; the single bolt of
    # another one does not earn it a link.
    assert any("produce_part_cadquery_logo (4 parts)" in text for text in texts)
    assert not any("produce_part_step" in text for text in texts)


#
# End to end
#


@pytest.mark.slow
def test_render_assembly_guide_html():
    """Export an assembly to an HTML assembly instruction book"""
    ctx = pc.init("examples")
    prj = ctx.get_project(CONNECT_PACKAGE)
    assert prj is not None
    output_dir = tempfile.mkdtemp()

    path = prj.render_assembly_guide(CONNECT_ASSEMBLY, "html", output_dir=output_dir, ignore_manufacturability=True)

    assert path == os.path.join(output_dir, CONNECT_ASSEMBLY + ".html")
    with open(path) as f:
        html = f.read()

    pages = re.findall(r'<section class="page" id="page-(\d+)" data-title="([^"]*)">', html)
    titles = [title for _, title in pages]
    # A title page, the bill of materials, the assembly, its steps, and links.
    assert titles[0] == CONNECT_ASSEMBLY
    assert titles[1] == "Bill of Materials"
    assert titles[-1] == "Links"
    assert "%s: step 1" % CONNECT_ASSEMBLY in titles
    assert "<h1>%s: step 1 of 7</h1>" % CONNECT_ASSEMBLY in html
    # The first step of this assembly asks for a gap of its own; the rest are
    # spaced by half of the largest dimension of the two items.
    assert "the two are shown 30.0mm apart" in html
    assert "Exploded view" in html
    # Every illustration is carried by the document itself.
    assert "data:image/svg+xml;base64," in html
    assert 'src="/' not in html


def test_assembly_guide_data_carries_the_same_document_with_its_pictures():
    """The instruction book as data, for the IDE's viewer

    The same document 'render_assembly_guide()' writes to a file, so what the
    viewer's Instructions tab shows and what the printed book says cannot drift
    apart -- only the pictures travel differently, inline rather than as files
    that are deleted the moment the document is built.
    """
    ctx = pc.init("examples")
    prj = ctx.get_project(CONNECT_PACKAGE)
    assert prj is not None

    data = prj.assembly_guide_data(CONNECT_ASSEMBLY, ignore_manufacturability=True)

    titles = [page["title"] for page in data["pages"]]
    assert titles[0] == CONNECT_ASSEMBLY
    assert titles[1] == "Bill of Materials"
    assert titles[-1] == "Links"
    assert "%s: step 1" % CONNECT_ASSEMBLY in titles

    images = [
        image
        for page in data["pages"]
        for block in page["blocks"]
        if block["type"] == "images"
        for image in block["images"]
    ]
    assert images
    # Carried, not pointed at: nothing here is a path into a directory that no
    # longer exists.
    assert all(image["src"].startswith("data:") for image in images)
    assert all("path" not in image for image in images)


def test_assembly_guide_data_of_a_missing_assembly_is_none():
    ctx = pc.init("examples")
    prj = ctx.get_project(CONNECT_PACKAGE)
    assert prj is not None

    assert prj.assembly_guide_data("no-such-assembly") is None


@pytest.mark.slow
def test_render_assembly_guide_pdf():
    """Export an assembly to a PDF assembly instruction book"""
    ctx = pc.init("examples")
    prj = ctx.get_project(CONNECT_PACKAGE)
    assert prj is not None
    output_dir = tempfile.mkdtemp()

    path = prj.render_assembly_guide(CONNECT_ASSEMBLY, "pdf", output_dir=output_dir, ignore_manufacturability=True)

    assert path == os.path.join(output_dir, CONNECT_ASSEMBLY + ".pdf")
    with open(path, "rb") as f:
        pdf = f.read()

    assert pdf.startswith(b"%PDF")
    # One page per step at the very least.
    assert pdf.count(b"/Type /Page\n") >= 7


@pytest.mark.slow
def test_render_assembly_guide_sub_assemblies():
    """An embedded sub-assembly is documented before the assembly that uses it"""
    ctx = pc.init("examples")
    prj = ctx.get_project("//produce_assembly_assy")
    assert prj is not None
    output_dir = tempfile.mkdtemp()

    path = prj.render_assembly_guide("logo_embedded", "html", output_dir=output_dir, ignore_manufacturability=True)

    with open(path) as f:
        html = f.read()

    titles = re.findall(r'<section class="page" id="page-\d+" data-title="([^"]*)">', html)

    # The head is embedded in the ASSY file of the assembly that uses it, so it
    # is documented under its own name, and before the assembly that uses it:
    # it has to exist before that one can be put together.
    assert "logo_embedded_head" in titles
    assert titles.index("logo_embedded_head: step 1") < titles.index("logo_embedded: step 1")
    assert "<h1>Assembly: logo_embedded_head</h1>" in html
    assert "<h1>logo_embedded_head: step 1 of 1</h1>" in html
    # The container the root node of an ASSY file creates is not a sub-assembly
    # of its own: the top level assembly is documented once, with its own steps.
    assert titles.count("logo_embedded") == 2  # the title page and its own page
    assert "<h1>logo_embedded: step 3 of 3</h1>" in html
    # What the ASSY file says about its nodes: the container node's description
    # on the sub-assembly's own page, and the first item's - which no step
    # places - on the page of the assembly it starts.
    assert "<p>The skull, made of two identical halves.</p>" in html
    assert "<p>Start with bone1.</p>" in html
    assert "<p>The first of the two crossed bones, laid flat.</p>" in html


@pytest.mark.slow
def test_render_assembly_guide_refuses_a_non_manufacturable_assembly():
    """The instruction book of an assembly nobody is meant to build is refused"""
    ctx = pc.init("examples")
    prj = ctx.get_project("//produce_assembly_assy")
    output_dir = tempfile.mkdtemp()

    with pytest.raises(NotManufacturableError):
        prj.render_assembly_guide("logo", "pdf", output_dir=output_dir)

    assert not os.path.exists(os.path.join(output_dir, "logo.pdf"))
