name: CI on Linux, MacOS and Windows

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          # False negatives on Windows for pytest result evaluation
          - os: "windows-latest"
            python-version: "3.11"
          - os: "windows-latest"
            python-version: "3.12"
    runs-on: ${{ matrix.os }}
    if: "!startsWith(github.event.head_commit.message, 'Version updated')"

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -r partcad/requirements.txt
          # pip install -r partcad-cli/requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        run: |
          pytest -x -p no:error-for-skips
