name: Python modules (test)

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: latest
          activate-environment: pc-conda-env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -r partcad/requirements.txt
          # pip install -r partcad-cli/requirements.txt
      - name: Test with pytest
        env:
          PYTHONPATH: partcad/src
          PYTHONWARNINGS: ignore
        run: |
          pytest -x -p no:error-for-skips
